version: '3.3'
services:
   mongo:
      image: mongo:latest
      hostname: mongodb
      ports:
        - "0.0.0.0:27017:27017/tcp"
      restart: always
      logging:
         options:
           max-size: 1g
      environment:
         - MONGO_INITDB_ROOT_USERNAME=mongoadmin
         - MONGO_INITDB_ROOT_PASSWORD=bdung
      volumes:
         - mongo_data_container:/data/db
      networks:
        - db_net
      expose:
        - "8080"
networks:
   db_net:
volumes:
   mongo_data_container:
